#!/usr/bin/env php
<?php

use CasaHugo\Secrets\{
    DotenvVault,
    SodiumVault,
    Command\SecretsDecryptToLocalCommand,
    Command\SecretsEncryptFromLocalCommand,
    Command\SecretsGenerateKeysCommand,
    Command\SecretsListCommand,
    Command\SecretsRemoveCommand,
    Command\SecretsSetCommand
};
use Symfony\Component\Console\Application;


set_time_limit(0);

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

$application = new Application();

$directory = getopt('', ['dir:'])['dir'] ?? null;

if (false === is_string($directory)) {
    echo "Argument --dir is missing" . PHP_EOL;
    exit;
}

$vault = new SodiumVault($directory);
$localVault = new DotenvVault($directory);

$application->addCommands([
    new SecretsDecryptToLocalCommand($vault, $localVault),
    new SecretsEncryptFromLocalCommand($vault, $localVault),
    new SecretsGenerateKeysCommand($vault, $localVault),
    new SecretsListCommand($vault, $localVault),
    new SecretsSetCommand($vault, $localVault),
    new SecretsRemoveCommand($vault, $localVault)
]);

try {
    $application->run();
} catch (Throwable $exception) {
    echo $exception->getMessage();
}

